### ISSUE TITLE
Request for crates

### ISSUE THREAD

**Issue by Patschkowski** [alire-project/alire-crates-ci#1]
Hi,

I see that this project already supports several crates. Is there a way to help to get support for additional crates?

Crates that would be interesting for my scenario are:

- AWS (Ada Web Server)
- Win32Ada
- GNATCOM / GWindows
- AZip

Thanks

**Comment by mosteo** [comment]
Thank you for these suggestions. I have moved them to our dedicated issue in https://github.com/alire-project/alire/issues/193
