### ISSUE TITLE
Community repository for Arch Linux

### ISSUE THREAD

**Issue by mgrojo** [alire-project/alire-crates-ci#6]
I've taken a look at the status of my crate play_2048, and I've seen that it fails in Arch Linux due to a failed dependency on libcsfml.

https://alire-crate-ci.ada.dev/status/pl/play_2048/1.0.0/linux/arch/gnat=10.2.1/play_2048-1.0.0.yaml.log

It seems ASFML compiled in the pull request checks for Arch.
https://github.com/alire-project/alire-index/runs/3075928215?check_suite_focus=true

Maybe the Community repository is missing in the case? The package is there:
https://archlinux.org/packages/community/x86_64/csfml/

On the other hand, for Fedora, would it compile if I add these package as origin?:
https://fedora.pkgs.org/35/fedora-x86_64/CSFML-2.5.1-3.fc35.i686.rpm.html

**Comment by mosteo** [comment]
Unfortunately the log for ASFML has expired already. That said, I've tested locally with the same Arch docker image and it builds properly in Arch, something else is happening. 

The problem in Fedora is unrelated, being a separate bug with unexpected verbosity from `dnf`, but the external definition is already correct.

**Comment by mosteo** [comment]
It turns out the test is much older than when the external definitions of csfml for Arch and Fedora were added. Next time the tester picks up play_2048 it should pass.
